# Generated by Django 3.2.5 on 2022-07-12 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_films'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Films',
            new_name='Film',
        ),
    ]
