# Generated by Django 3.2.5 on 2022-07-16 11:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_rename_films_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='content',
            field=models.TextField(default='This is a nice movie'),
        ),
        migrations.AddField(
            model_name='film',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='film',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='film',
            name='users',
        ),
        migrations.AddField(
            model_name='film',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='films.user'),
            preserve_default=False,
        ),
    ]
