# Generated by Django 3.2.5 on 2022-07-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_auto_20220716_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='users',
            new_name='user',
        ),
    ]
