# Generated by Django 3.2.5 on 2022-07-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_rename_users_film_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='photo',
            field=models.ImageField(default=1, upload_to='photo/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
